name: Build APK

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: pycom/app
          buildozer_version: stable
          command: buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: PergaminoPrecios-APK
          path: pycom/app/bin/*.apk
